<div class="space-y-4" wire:poll.5s.visible>
    @if(session('success'))<div class="rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ session('success') }}</div>@endif
    <div class="flex gap-2 overflow-x-auto rounded-2xl bg-white p-2 shadow-sm">
        @foreach(['inbox' => 'Inbox', 'knowledge' => 'Knowledge Base', 'settings' => 'AI Settings', 'logs' => 'AI Logs'] as $key => $label)
            <button wire:click="$set('tab','{{ $key }}')" class="min-h-11 whitespace-nowrap rounded-xl px-4 text-sm font-semibold {{ $tab === $key ? 'bg-slate-900 text-white' : 'bg-slate-50 text-slate-600' }}">{{ $label }}</button>
        @endforeach
    </div>

    @if($tab === 'inbox')
    <div class="grid h-[calc(100dvh-170px)] min-h-[500px] max-h-none overflow-hidden rounded-[24px] border border-black/[0.06] bg-white shadow-[0_20px_60px_rgba(25,20,18,.08)] sm:h-[calc(100dvh-190px)] lg:h-[calc(100dvh-220px)] lg:min-h-[620px] lg:max-h-[860px] lg:grid-cols-[340px_1fr] lg:rounded-[28px]">
        <aside class="{{ $selected ? 'hidden lg:block' : 'block' }} min-h-0 border-b border-slate-200 lg:border-b-0 lg:border-r">
            <div class="space-y-2 border-b p-3"><input wire:model.live.debounce.300ms="search" class="w-full rounded-xl border-slate-200 text-sm" placeholder="Search customers"><select wire:model.live="filter" class="w-full rounded-xl border-slate-200 text-sm"><option value="all">All</option><option value="unread">Unread</option><option value="AI_ACTIVE">AI Active</option><option value="HUMAN_ACTIVE">Human Active</option><option value="AI_PAUSED">Needs attention</option><option value="RESOLVED">Resolved</option></select></div>
            <div class="h-[calc(100%-129px)] overflow-y-auto overscroll-contain bg-gradient-to-b from-white to-[#faf8f7]">@forelse($conversations as $conversation)<button wire:click="selectConversation('{{ $conversation->id }}')" class="block w-full rounded-none border-b border-black/[0.05] p-4 text-left transition hover:bg-[#fff7f3] {{ $selectedConversationId === $conversation->id ? 'bg-gradient-to-r from-red-50 via-orange-50 to-white shadow-[inset_3px_0_0_#b91c1c]' : '' }}"><div class="flex items-center justify-between gap-2"><span class="truncate text-sm font-bold text-slate-900">{{ $conversation->customer->display_name ?: 'Guest '.substr($conversation->id,0,6) }}</span><span class="rounded-full px-2 py-1 text-[9px] font-bold {{ $conversation->mode->value === 'AI_ACTIVE' ? 'bg-red-50 text-red-700' : ($conversation->mode->value === 'HUMAN_ACTIVE' ? 'bg-orange-50 text-orange-700' : 'bg-slate-100 text-slate-600') }}">{{ str_replace('_',' ',$conversation->mode->value) }}</span></div><p class="mt-1 truncate text-xs text-slate-500">{{ optional($conversation->messages->first())->content ?: 'New conversation' }}</p>@if($conversation->admin_unread_count)<span class="mt-2 inline-block rounded-full bg-gradient-to-r from-red-700 to-orange-600 px-2 py-0.5 text-[10px] text-white shadow-sm">{{ $conversation->admin_unread_count }} new</span>@endif</button>@empty<div class="p-8 text-center text-sm text-slate-500">No conversations yet.</div>@endforelse</div>
        </aside>
        <section class="{{ $selected ? 'flex' : 'hidden lg:flex' }} min-h-0 flex-col overflow-hidden bg-[#f7f5f3]">@if($selected)
            <header class="flex flex-wrap items-center justify-between gap-3 border-b border-black/[0.06] bg-white/95 p-3 backdrop-blur-xl sm:p-4">
                <div class="flex min-w-0 items-center gap-2"><button wire:click="closeConversation" class="grid h-10 w-10 flex-none place-items-center border border-black/[0.06] bg-white text-slate-700 lg:hidden" aria-label="Back to conversations"><svg class="h-5 w-5" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="m15 18-6-6 6-6"/></svg></button><div class="min-w-0"><h2 class="truncate font-bold">{{ $selected->customer->display_name ?: 'Guest customer' }}</h2><p class="truncate text-xs text-slate-500">{{ $selected->channel }}@if($selected->assignedAdmin) · Assigned to {{ $selected->assignedAdmin->name }}@endif</p></div></div>
                <div class="flex w-full flex-wrap gap-2 sm:w-auto">
                    @if($selected->mode->value === 'AI_ACTIVE')<button wire:click="takeOver" wire:loading.attr="disabled" wire:target="takeOver" class="min-h-11 flex-1 rounded-full bg-slate-950 px-4 text-xs text-white disabled:opacity-50 sm:flex-none">Take Over</button>
                    @elseif($selected->mode->value === 'AI_PAUSED')<button wire:click="takeOver" wire:loading.attr="disabled" wire:target="takeOver" class="min-h-11 flex-1 rounded-full bg-slate-950 px-4 text-xs text-white disabled:opacity-50 sm:flex-none">Handle as Human</button><button wire:click="resumeAi" wire:loading.attr="disabled" wire:target="resumeAi" class="min-h-11 flex-1 rounded-full bg-gradient-to-r from-red-700 to-orange-600 px-4 text-xs text-white disabled:opacity-50 sm:flex-none">Return to AI</button>
                    @elseif($selected->mode->value === 'HUMAN_ACTIVE')<button wire:click="resumeAi" wire:loading.attr="disabled" wire:target="resumeAi" class="min-h-11 flex-1 rounded-full bg-gradient-to-r from-red-700 to-orange-600 px-4 text-xs text-white disabled:opacity-50 sm:flex-none">Return to AI</button>@endif
                    <button wire:click="resolve" wire:loading.attr="disabled" wire:target="resolve" class="min-h-11 flex-1 rounded-full border border-slate-200 bg-white px-4 text-xs disabled:opacity-50 sm:flex-none">Resolve</button>
                </div>
            </header>
            <div class="border-b px-4 py-3 {{ $selected->mode->value === 'AI_ACTIVE' ? 'border-red-100 bg-gradient-to-r from-red-50 via-orange-50 to-white text-red-950' : ($selected->mode->value === 'HUMAN_ACTIVE' ? 'border-orange-100 bg-gradient-to-r from-orange-50 to-white text-orange-950' : ($selected->mode->value === 'AI_PAUSED' ? 'border-red-100 bg-gradient-to-r from-red-100 to-orange-50 text-red-950' : 'border-slate-100 bg-slate-50 text-slate-700')) }}">
                <div class="flex items-start gap-3"><span class="mt-1.5 h-2.5 w-2.5 flex-none rounded-full shadow-[0_0_0_4px_rgba(185,28,28,.08)] {{ $selected->mode->value === 'AI_ACTIVE' ? 'bg-red-600' : ($selected->mode->value === 'HUMAN_ACTIVE' ? 'bg-orange-500' : ($selected->mode->value === 'AI_PAUSED' ? 'bg-red-700' : 'bg-slate-400')) }}"></span><div><p class="text-xs font-bold">{{ $selected->mode->value === 'AI_ACTIVE' ? 'AI is handling this conversation' : ($selected->mode->value === 'HUMAN_ACTIVE' ? 'A human is handling this conversation' : ($selected->mode->value === 'AI_PAUSED' ? 'AI is paused — this conversation needs attention' : 'Conversation resolved')) }}</p><p class="mt-0.5 text-[11px] opacity-75">{{ $selected->mode->value === 'AI_ACTIVE' ? 'Sending a manual reply will automatically take over before your message is delivered.' : ($selected->mode->value === 'HUMAN_ACTIVE' ? 'AI cannot send customer-facing replies until you return this conversation to AI.' : ($selected->mode->value === 'AI_PAUSED' ? 'Choose Handle as Human or safely return it to AI.' : 'A new customer message may reopen this conversation.')) }}</p></div></div>
            </div>
            <div wire:key="support-thread-{{ $selected->id }}-{{ optional($selected->messages->last())->id ?: 'empty' }}" class="min-h-0 flex-1 space-y-4 overflow-y-auto overscroll-contain bg-[radial-gradient(circle_at_top_left,rgba(251,146,60,.08),transparent_32%),linear-gradient(to_bottom,#faf9f8,#f2f0ee)] p-4 sm:p-6" x-data x-init="$nextTick(() => { $el.scrollTop = $el.scrollHeight })">@foreach($selected->messages as $message)@if(in_array($message->content_type, ['PRODUCT_CARD', 'PRODUCT_CAROUSEL']))<div class="ml-auto max-w-[86%] rounded-2xl border border-orange-100 bg-white p-4 text-sm shadow-sm"><p class="text-[10px] font-bold tracking-wide text-orange-700">AI PRODUCT RECOMMENDATION</p><p class="mt-1 text-slate-600">{{ count(data_get($message->payload, 'products', [])) }} verified product recommendation{{ count(data_get($message->payload, 'products', [])) === 1 ? '' : 's' }} shown to the customer.</p></div>@elseif($message->content_type === 'ACTION_RESULT')<div class="ml-auto max-w-[86%] rounded-2xl border border-emerald-100 bg-emerald-50 px-4 py-3 text-sm text-emerald-900 shadow-sm"><p class="text-[10px] font-bold tracking-wide text-emerald-700">CUSTOMER COMMERCE ACTION</p><p class="mt-1">{{ $message->content }}</p></div>@else<div class="max-w-[86%] sm:max-w-[75%] {{ $message->sender_type === 'CUSTOMER' ? '' : 'ml-auto' }}"><span class="mb-1.5 block px-1 text-[10px] font-bold tracking-wide {{ $message->sender_type === 'CUSTOMER' ? 'text-slate-500' : 'text-right text-slate-500' }}">{{ $message->sender_type === 'ADMIN' ? optional($message->senderUser)->name ?: 'ADMIN' : $message->sender_type }}</span><div class="px-4 py-3 text-sm leading-relaxed shadow-[0_10px_30px_rgba(28,22,18,.08)] {{ $message->sender_type === 'CUSTOMER' ? 'rounded-[8px_24px_24px_24px] border border-white bg-white text-slate-800' : ($message->sender_type === 'AI' ? 'rounded-[24px_8px_24px_24px] bg-gradient-to-br from-red-700 via-red-600 to-orange-500 text-white' : 'rounded-[24px_8px_24px_24px] bg-gradient-to-br from-slate-950 to-slate-800 text-white') }}"><p class="whitespace-pre-wrap break-words">{{ $message->content }}</p></div></div>@endif @endforeach</div>
            @if($selected->mode->value !== 'RESOLVED')<form wire:submit="sendReply" class="border-t border-black/[0.06] bg-white/95 p-2.5 pb-[max(.625rem,env(safe-area-inset-bottom))] backdrop-blur-xl sm:p-4"><div class="flex items-center gap-2 rounded-full border border-black/[0.07] bg-[#f3f2f1] p-1.5 shadow-inner"><input wire:model="reply" class="min-h-11 min-w-0 flex-1 border-0 bg-transparent px-3 text-[16px] shadow-none outline-none ring-0 focus:border-0 focus:ring-0 sm:text-sm" maxlength="2000" placeholder="{{ $selected->mode->value === 'AI_ACTIVE' ? 'Reply and take over…' : 'Message customer…' }}"><button type="submit" wire:loading.attr="disabled" wire:target="sendReply" class="grid h-11 min-h-11 w-11 flex-none place-items-center rounded-full bg-gradient-to-br from-red-700 to-orange-500 p-0 text-white shadow-[0_8px_20px_rgba(185,28,28,.25)] disabled:opacity-50 sm:w-auto sm:grid-flow-col sm:gap-2 sm:px-5" aria-label="{{ $selected->mode->value === 'AI_ACTIVE' ? 'Send message and take over conversation' : 'Send message' }}"><svg class="h-5 w-5" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24" aria-hidden="true"><path d="m22 2-7 20-4-9-9-4Z"/><path d="M22 2 11 13"/></svg><span class="hidden text-sm sm:inline">{{ $selected->mode->value === 'AI_ACTIVE' ? 'Send & Take Over' : 'Send' }}</span></button></div>@if($selected->mode->value === 'AI_ACTIVE')<p class="mt-1.5 px-2 text-[10px] text-slate-500 sm:hidden">Sending a reply will switch this conversation to human support.</p>@endif @error('reply')<p class="mt-2 px-2 text-xs text-red-600">{{ $message }}</p>@enderror</form>@endif
        @else<div class="grid flex-1 place-items-center p-8 text-center text-sm text-slate-500"><div><div class="mx-auto mb-3 grid h-12 w-12 place-items-center rounded-full bg-slate-100"><svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M8 10h8M8 14h5M5 20l-1 1v-4a8 8 0 1 1 3 3H5z"/></svg></div><p class="font-semibold text-slate-700">Select a conversation</p><p class="mt-1 text-xs">Review its ownership before replying or taking over.</p></div></div>@endif</section>
    </div>
    @elseif($tab === 'knowledge')
    <div class="grid gap-4 lg:grid-cols-[380px_1fr]"><form wire:submit="saveKnowledge" class="space-y-3 rounded-2xl bg-white p-5 shadow-sm"><div class="flex items-center justify-between gap-3"><h2 class="font-bold">{{ $editingKnowledgeId ? 'Edit knowledge' : 'Add approved knowledge' }}</h2>@if($editingKnowledgeId)<button type="button" wire:click="cancelKnowledgeEdit" class="rounded-full border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-700">Cancel</button>@endif</div><input wire:model="knowledgeTitle" class="w-full rounded-xl border-slate-200" placeholder="Title"><input wire:model="knowledgeCategory" class="w-full rounded-xl border-slate-200" placeholder="Category"><textarea wire:model="knowledgeContent" rows="10" class="w-full rounded-xl border-slate-200" placeholder="Policy or FAQ content"></textarea><button class="min-h-12 rounded-full bg-gradient-to-r from-red-700 to-orange-600 px-5 text-sm font-semibold text-white shadow-[0_8px_20px_rgba(185,28,28,.2)]">{{ $editingKnowledgeId ? 'Save new version' : 'Save and index' }}</button></form><div class="space-y-2">@foreach($knowledge as $document)<article class="rounded-2xl bg-white p-4 shadow-sm"><div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div class="min-w-0"><h3 class="font-bold">{{ $document->title }}</h3><p class="text-xs text-slate-500">Version {{ $document->version }} · {{ $document->status }} · {{ $document->category ?: 'Uncategorized' }}</p><p class="mt-2 line-clamp-2 text-sm text-slate-600">{{ $document->content }}</p></div><div class="grid w-full grid-cols-2 gap-2 sm:flex sm:w-auto"><button wire:click="editKnowledge('{{ $document->id }}')" class="min-h-11 rounded-full border border-slate-200 bg-white px-4 text-xs font-semibold text-slate-700 transition hover:border-slate-300 hover:bg-slate-50">Edit</button>@if($document->status === 'ACTIVE')<button wire:click="disableKnowledge('{{ $document->id }}')" wire:confirm="Deactivate this knowledge? The AI will stop using it immediately." class="min-h-11 rounded-full bg-gradient-to-r from-red-700 to-orange-600 px-4 text-xs font-semibold text-white shadow-sm">Deactivate</button>@elseif($document->status === 'DISABLED')<button wire:click="activateKnowledge('{{ $document->id }}')" class="min-h-11 rounded-full bg-emerald-600 px-4 text-xs font-semibold text-white shadow-sm">Reactivate</button>@endif</div></div></article>@endforeach</div></div>
    @elseif($tab === 'settings')
    <div class="rounded-2xl bg-white p-6 shadow-sm"><h2 class="font-bold">Global AI kill switch</h2><p class="mt-1 text-sm text-slate-500">Manual customer/admin chat remains available while AI is off.</p><div class="mt-5 flex items-center gap-4"><span class="rounded-full px-3 py-1 text-xs font-bold {{ $settings?->enabled ? 'bg-emerald-100 text-emerald-800' : 'bg-red-100 text-red-800' }}">{{ $settings?->enabled ? 'ENABLED' : 'DISABLED' }}</span>@if(auth()->user()->isOwner())<button wire:click="toggleAi" class="min-h-11 bg-slate-900 px-5 text-sm text-white">Turn {{ $settings?->enabled ? 'off' : 'on' }}</button>@endif</div><dl class="mt-6 grid gap-3 text-sm sm:grid-cols-2"><div><dt class="text-slate-500">Provider</dt><dd class="font-semibold">{{ $settings?->provider }}</dd></div><div><dt class="text-slate-500">Model</dt><dd class="font-semibold">{{ $settings?->model }}</dd></div><div><dt class="text-slate-500">Embedding</dt><dd class="font-semibold">{{ $settings?->embedding_model }}</dd></div></dl></div>
    @else
    <div class="overflow-x-auto rounded-2xl bg-white shadow-sm"><table class="w-full text-left text-sm"><thead><tr class="border-b"><th class="p-4">Started</th><th class="p-4">Status</th><th class="p-4">Model</th><th class="p-4">Conversation</th><th class="p-4">Error</th></tr></thead><tbody>@foreach($runs as $run)<tr class="border-b"><td class="p-4">{{ $run->started_at?->diffForHumans() }}</td><td class="p-4">{{ $run->status }}</td><td class="p-4">{{ $run->model }}</td><td class="p-4 font-mono text-xs">{{ $run->conversation_id }}</td><td class="p-4 text-xs text-red-700">{{ $run->error_code }}</td></tr>@endforeach</tbody></table></div>
    @endif
</div>
